name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
     
      - uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - name: Install dependencies
        run: npm install
     
      - name: Install Playwright Browsers
        run: npx playwright install
     
      - name: Run Playwright tests with Video Recording
        run: npx playwright test --video=on
        env:
          PLAYWRIGHT_VIDEO_DIR: ${{ github.workspace }}/playwright-video

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
     
      - name: Convert video to MP4
        run: |
          ffmpeg -y -i ${{ github.workspace }}/playwright-video/video.webm -c:v libx264 -preset medium -c:a aac -b:a 128k -pix_fmt yuv420p ${{ github.workspace }}/playwright-video/video.mp4
     
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
     
      - uses: actions/upload-artifact@v3
        if: always()
        with:    
          name: test-results
          path: test-results/
          retention-days: 30
          
      - uses: actions/upload-artifact@v3
        if: always()
        with:    
          name: playwright-video
          path: playwright-video/
          retention-days: 30
